import Gnb from "@/components/common/Gnb";
import Header from "@/components/common/Header";
import MyStudyModal from "@/components/profile/MyStudyModal";
import ProfileCard from "@/components/profile/ProfileCard";
import ProfileTabs from "@/components/profile/ProfileTabs";

export const generateMetadata = async ({
    params,
}: {
    params: Promise<{ profileId: string }>;
}) => {
    return {
        title: `프로필 ${(await params).profileId}  | Studium`,
        description: "Generated by Next.js",
    };
};

export default async function page({
    params,
}: {
    params: Promise<{ profileId: string }>;
}) {
    const { profileId } = await params;
    console.log(profileId);

    return (
        <>
            <Header isMyPage={true}> </Header>
            <div className="flex h-screen items-center justify-center pt-15.5">
                <div className="bg-gray100 h-full w-screen overflow-hidden pb-4">
                    <ProfileCard id={profileId} />
                    <ProfileTabs id={profileId} />
                    <MyStudyModal />
                </div>
            </div>
            <Gnb />
        </>
    );
}
