import "@/css/index.css";

export const metadata = {
    title: "스터디 수정 | Studium",
    description: "Generated by Next.js",
};

export default function layout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <>
            <div className="m-auto h-screen w-screen max-w-sm">{children}</div>
        </>
    );
}
