import Gnb from "@/components/common/Gnb";
import Header from "@/components/common/Header";

export const metadata = {
    title: "리워드상점 | Studium",
    description: "Generated by Next.js",
};

export default function layout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <>
            <Header notLogin={true}>리워드 상점</Header>
            {children}
            <Gnb />
        </>
    );
}
