import type { Metadata } from "next";

export const metadata: Metadata = {
    title: "Studium",
    description: "Generated by Next.js",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="ko">
            <body>{children}</body>
        </html>
    );
}
