import type { Metadata } from "next";
import "../css/index.css";
import localfont from "next/font/local";
const pretendard = localfont({
    variable: "--font-pretendard",
    src: "../assets/fonts/PretendardVariable.woff2",
});

export const metadata: Metadata = {
    title: "Studium",
    description: "Generated by Next.js",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
<<<<<<< HEAD
        <html lang="ko" suppressHydrationWarning>
            <body className={`${pretendard.variable}`}>
                <Header />
                {children}
                <Gnb />
            </body>
=======
        <html lang="ko">
            <body className={`${pretendard.variable}`}>{children}</body>
>>>>>>> df95fab0e3f7c795aa0de0b3c9f4449c67d76ef4
        </html>
    );
}
