import type { Metadata } from "next";
import "../css/index.css";
import localfont from "next/font/local";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import AuthInitializer from "@/components/login/AuthInitializer";
import TanstackProvider from "@/providers/TanstackProvider";

const pretendard = localfont({
    variable: "--font-pretendard",
    src: "../assets/fonts/PretendardVariable.woff2",
});

export const metadata: Metadata = {
    title: "Studium",
    description: "Generated by Next.js",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="ko" suppressHydrationWarning>
            <body
                className={`${pretendard.variable} dark:bg-dark-bg duration-200 ease-in`}
            >
                <TanstackProvider> {children}</TanstackProvider>
                <ToastContainer limit={1} />
                <AuthInitializer />
            </body>
        </html>
    );
}
