export const metadata = {
    title: "내 정보 수정 | Studium",
    description: "Generated by Next.js",
};

export default function layout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return <>{children}</>;
}
