export const metadata = {
    title: "서바이벌 | Studium",
    description: "Generated by Next.js",
};

export default function layout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return <div>{children}</div>;
}
