import Gnb from "@/components/common/Gnb";
import Header from "@/components/common/Header";

export const metadata = {
    title: "마이페이지 | Studium",
    description: "Generated by Next.js",
};

export default function layout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <>
            <Header />
            {children}
            <Gnb />
        </>
    );
}
